[package]
name = "ruRAND-host"
version.workspace = true
edition = "2024"
authors = ["Dilshod Tadjibaev (@antimora)"]
license = "MIT OR Apache-2.0"
readme = "README.md"
build = false
description = "Random number generation for Ruda."
repository = "https://github.com/shuqi2077/RUDA"

[lib]
name = "rurand_host"
path = "src/lib.rs"

[features]
default = ["std"]
std = ["ruda-core/std", "half/std"]

[dependencies.half]
version = "2.7.1"
features = [ "alloc", "num-traits", "serde",]
default-features = false


[dependencies.ruda-core]
path = "../../ruda-core"
version = "0.1.3"
default-features = false
features = ["tensor-host-storage"]
